import type { BlockName, CollectionName } from './content-schema.js';

/**
 * Initial content, copied from what the live site showed before the CMS existed,
 * so the first deploy looks identical. Edited afterwards from the admin panel.
 */
const u = (id: string, w = 1000) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=85`;

// Page blocks are left out: until the admin saves a page, the website shows its built-in copy.
export const seedBlocks: Partial<Record<BlockName, Record<string, unknown>>> = {
  hero: {
    eyebrow: 'Performance marketing • Creator ads • Web',
    headline: 'We turn organic clips into scaled accounts.',
    sub: 'CLYX Media runs the creator whitelisting + performance engine behind brands that sell — Meta & Google ads, content, branding, and websites built for one job: conversion.',
  },
};

export const seedCollections: Record<CollectionName, Record<string, unknown>[]> = {
  stats: [
    { value: '₹1Cr+', label: 'Ad Spend Managed', detail: 'Across Meta & Google ad accounts' },
    { value: '5X+', label: 'Average ROAS Lift', detail: 'Whitelisted vs Standard brand ads' },
    { value: '250+', label: 'Active Creators', detail: 'Fashion, Beauty, Food, Tech benches' },
    { value: '₹10Cr+', label: 'Revenue Generated', detail: 'Delivered for high-growth D2C brands' },
  ],
  campaigns: [
    { client: 'KULTURE SKIN', category: 'CREATOR COMMERCE', roas: '3.4X ROAS SCALE', spend: '', status: 'Scaling', desc: 'Turned organic beauty creator clips into a repeatable Meta whitelisting engine.', img: u('photo-1522337360788-8b13dee7a37e'), ctaText: 'View Case Study', ctaUrl: '/case-studies' },
    { client: 'NOVA NUTRITION', category: 'PERFORMANCE ADS', roas: '42% LOWER CPA', spend: '', status: 'Scaling', desc: 'Rapid creative iteration testing 45+ hooks weekly to aggressively scale media spend.', img: u('photo-1541643600914-78b084683601'), ctaText: 'View Case Study', ctaUrl: '/case-studies' },
    { client: 'MUTHA BEAUTY', category: 'CULTURE FIRST', roas: '10M+ IMPRESSIONS', spend: '', status: 'Scaling', desc: 'Editorial and high-aesthetic brand storytelling engineered to convert on TikTok & Reels.', img: u('photo-1515886657613-9f3515b0c78f'), ctaText: 'View Case Study', ctaUrl: '/case-studies' },
    { client: 'ORBIT LABS', category: 'CONVERSION TECH', roas: '+28% CVR LIFT', spend: '', status: 'Scaling', desc: 'Custom headless storefronts tuned for 0.4s load times and lightning checkout flows.', img: u('photo-1496747611176-843222e1e57c'), ctaText: 'View Case Study', ctaUrl: '/case-studies' },
    { client: 'HALO D2C', category: 'UGC ENGINE', roas: '4.1X BLENDED ROAS', spend: '', status: 'Scaling', desc: 'Built and managed a dedicated roster of 120+ micro-creators producing genuine hooks.', img: u('photo-1483985988355-763728e1935b'), ctaText: 'View Case Study', ctaUrl: '/case-studies' },
    { client: 'LUMEN WEAR', category: 'BRAND LAUNCH', roas: '2.8X FIRST-MONTH ROAS', spend: '', status: 'Scaling', desc: 'Launched a fashion label from zero with creator-led drops and full-funnel Meta ads.', img: u('photo-1529139574466-a303027c1d8b'), ctaText: 'View Case Study', ctaUrl: '/case-studies' },
  ],
  // Performance-marketing case studies: the card fields first, then everything on the case study's own page.
  // List fields hold one entry per line; "A | B | C" lines are split into columns on the page.
  caseStudies: [
    {
      brand: 'Kulture Skin',
      category: 'Skincare D2C / Meta Ads',
      headline: 'Scaled Meta spend 6x without breaking ROAS.',
      result: '3.4x ROAS',
      accent: '#FFDE59',
      image: u('photo-1612817288484-6f916006741a', 1400),
      detail: 'Kulture Skin was stuck at ₹3L a month on Meta with a 1.6x ROAS. We rebuilt the account structure, fed it creator-led creative every week and scaled spend to ₹18L a month at 3.4x blended ROAS.',
      highlights: 'Meta spend scaled from ₹3L to ₹18L a month\nBlended ROAS doubled from 1.6x to 3.4x\nPurchase tracking rebuilt with the Conversions API\n180+ creator ads tested in six months',
      industry: 'D2C skincare',
      market: 'India, metro-first',
      duration: '6 months',
      channels: 'Meta Ads, Instagram Reels, Google Search',
      adSpend: '₹3L → ₹18L / month',
      services: 'Meta Ads management, Creative strategy, UGC ad production, Landing page CRO, Tracking & attribution',
      requirement: 'Kulture Skin had a loyal organic following and a bestselling vitamin C serum, but paid growth had stalled. The founders came to us with a clear brief: scale Meta Ads past ₹15L a month without ROAS collapsing every time the budget went up, and stop relying on one hero ad that had been running for four months.',
      goals: 'Scale Meta spend from ₹3L to ₹15L+ a month\nHold a blended ROAS of 3x or better while scaling\nBuild a weekly creative pipeline so no single ad carries the account\nFix purchase tracking so decisions run on real numbers',
      challenges: 'Broken tracking | iOS signal loss and a misfiring pixel meant Meta saw only about 60% of real purchases, so the algorithm was optimising on bad data.\nCreative fatigue | One hero video drove 70% of spend. Every time its frequency crossed 3, CPA spiked and the whole account dipped.\nFragmented account | 23 ad sets with overlapping interest audiences were bidding against each other, and none of them left the learning phase.\nScaling crashes | Budget jumps of more than 20% reset learning, and ROAS fell to around 1.2x for days at a time.',
      approach: 'Fix the data first | Set up the Conversions API with server-side events and deduplication, lifting event match quality from 4.1 to 8.7 so Meta could see real buyers again.\nConsolidate the account | Collapsed 23 ad sets into one testing campaign and one broad Advantage+ scaling campaign, so budget sat where it learned fastest.\nCreative as targeting | Briefed 35 creators on proven angles (texture close-ups, 30-day routines, honest reviews) and tested 20–25 new hooks every week.\nScale on rules, not mood | Ads moved to scaling only after 3 days above target ROAS. Budgets rose 15–20% every 48 hours, with cost caps as guard rails.',
      execution: 'The account ran on a weekly loop: creative brief on Monday, new ads live by Thursday, performance review every Monday morning. Losing ads were cut within 72 hours, winners were re-cut into new hooks and formats, and every winning angle got its own landing page section so the click matched the promise.',
      deliverables: '180+ ad creatives across video, static and carousel\nConversions API and GA4 purchase tracking rebuilt\nTwo-campaign account structure (testing + Advantage+ scaling)\n4 angle-matched landing page variants\nWeekly performance report with next week\'s test plan',
      work: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=1200&q=85 | Skincare routine shoot for the creator hook tests\nhttps://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=85 | Weekly ROAS and CPA dashboard shared with the founders\nhttps://images.unsplash.com/photo-1552581234-26160f608093?auto=format&fit=crop&w=1200&q=85 | Monday creative review: choosing next week\'s hooks',
      metrics: '3.4x | Blended ROAS | up from 1.6x\n6x | Monthly ad spend | ₹3L to ₹18L\n-38% | Cost per purchase | while scaling\n2.3x | Hook rate | creator vs studio ads',
      comparison: 'Monthly ad spend | ₹3L | ₹18L\nBlended ROAS | 1.6x | 3.4x\nCost per purchase | ₹740 | ₹459\nWinning ads in rotation | 1 | 14\nMonthly revenue from Meta | ₹4.8L | ₹61L',
      resultsSummary: 'By month three, the account no longer depended on a single ad. By month six, Kulture Skin was spending six times more on Meta at more than double the return, with 14 winning ads in rotation and a creative pipeline that refreshes every week.',
      quote: 'Before CLYX, every time we raised the budget we lost money. Now we scale every month and know exactly which ad to put the money behind. The weekly reports alone changed how we run the business.',
      quoteName: 'Co-founder',
      quoteRole: 'Kulture Skin',
      learnings: 'Fix tracking before touching budget | Better signal improved CPA by 18% before a single new ad went live.\nCreative is the new targeting | With broad audiences, the hook decided who saw the ad, so creative volume became the main growth lever.\nScale in steps | 15–20% budget increases every 48 hours kept the algorithm stable, where big jumps reset it.',
    },
    {
      brand: 'Nova Nutrition',
      category: 'Supplements / Google Ads',
      headline: 'Cut CPA by 42% on Google Search and Shopping.',
      result: '-42% CPA',
      accent: '#003AA3',
      image: u('photo-1593095948071-474c5cc2989d', 1400),
      detail: 'Nova Nutrition was losing money on Google: rising CPCs, broad match waste and a Performance Max campaign eating brand searches. We rebuilt Search, Shopping and PMax around profit and cut cost per acquisition by 42% in four months.',
      highlights: '1,400+ negative keywords cut wasted search spend\nBrand searches separated from Performance Max\n120 product titles rewritten for Shopping\nMobile pages sped up from 5.2s to 1.4s',
      industry: 'Health & sports nutrition',
      market: 'Pan-India D2C',
      duration: '4 months',
      channels: 'Google Search, Shopping, Performance Max, YouTube',
      adSpend: '₹8L / month',
      services: 'Google Ads management, Product feed optimisation, Performance Max setup, Landing page CRO, Offer testing',
      requirement: 'Nova sells whey protein, plant protein and daily supplements. Google was their biggest channel, but cost per acquisition had climbed about 60% over two quarters while revenue stayed flat. They asked us to bring CPA down without cutting volume, and to tell them honestly which campaigns were making money and which were only spending it.',
      goals: 'Cut blended CPA by at least 30%\nStop paying for brand searches through Performance Max\nGet Shopping ads showing for high-margin products, not just the cheapest\nLift landing page conversion rate on mobile',
      challenges: 'Broad match waste | 38% of search spend went to irrelevant queries like "protein side effects" and "how to make protein powder at home".\nPMax eating brand searches | Performance Max was claiming brand searches people would have made anyway, which made its ROAS look far better than it really was.\nWeak product feed | Generic product titles and missing attributes kept Shopping ads out of high-intent searches like "whey isolate 2kg chocolate".\nSlow product pages | Mobile product pages took 5.2 seconds to load, and reviews sat four screens below the fold.',
      approach: 'Audit every rupee | Pulled 90 days of search terms, added 1,400+ negative keywords and moved winning queries into exact and phrase match campaigns.\nSeparate brand from prospecting | Ran brand search on its own small budget and excluded brand terms from PMax, so each campaign was judged on new customers.\nRebuild the feed | Rewrote 120 product titles with flavour, size and protein per serving, and split products into margin tiers with their own ROAS targets.\nFix the landing experience | Built faster mobile product pages with reviews, lab reports and a starter bundle above the fold.',
      execution: 'We worked in two-week sprints. The first stopped the waste (negatives and brand separation), the second rebuilt the product feed, and the third and fourth focused on landing pages and offer tests. Every change was measured against profit per order, not just ROAS.',
      deliverables: '1,400+ negative keywords and a rebuilt keyword structure\n120 rewritten product titles and a margin-tiered product feed\nSeparate brand, Search, Shopping and PMax campaigns\n3 mobile landing pages with starter bundles\nProfit-per-order reporting dashboard',
      work: 'https://images.unsplash.com/photo-1622484212850-eb596d769edc?auto=format&fit=crop&w=1200&q=85 | Product shots for the new Shopping feed and starter bundles\nhttps://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=85 | Search term audit: 38% of spend was going to irrelevant queries\nhttps://images.unsplash.com/photo-1533750349088-cd871a92f312?auto=format&fit=crop&w=1200&q=85 | Offer test plan: bundles vs flat discounts',
      metrics: '-42% | Cost per acquisition | within 4 months\n+61% | Landing page CVR | on mobile\n+24% | Average order value | from bundles\n2.9x | Blended ROAS | up from 1.8x',
      comparison: 'Cost per acquisition | ₹1,150 | ₹667\nWasted search spend | 38% | 7%\nMobile page load | 5.2s | 1.4s\nAverage order value | ₹1,690 | ₹2,095\nBlended ROAS | 1.8x | 2.9x',
      resultsSummary: 'Cutting wasted spend and separating brand from prospecting showed the real picture within weeks. Nova now acquires customers for 42% less on the same budget, and bundles raised order values enough to fund YouTube campaigns for new demand.',
      quote: 'CLYX was the first agency to show us where our Google money was actually going. Cutting the waste paid for their fee in the first month.',
      quoteName: 'Head of Growth',
      quoteRole: 'Nova Nutrition',
      learnings: 'Search terms tell the truth | The keyword list looked fine. The search terms report showed a third of the budget going to the wrong people.\nJudge PMax without brand | Once brand searches were excluded, PMax ROAS dropped on paper but new-customer growth went up.\nThe feed is the ad | Better product titles did more for Shopping than any bid change.',
    },
    {
      brand: 'Urban Loom',
      category: 'Fashion E-commerce / Festive sale',
      headline: '₹1.2Cr in 30 days from one festive sale.',
      result: '5.2x ROAS',
      accent: '#FFDE59',
      image: u('photo-1483985988355-763728e1935b', 1400),
      detail: 'Urban Loom\'s Diwali sale was always their biggest month, and their most chaotic. We planned it as a six-week performance campaign (warm up, launch, scale, close) and it delivered ₹1.2Cr in revenue at 5.2x ROAS.',
      highlights: 'Six-week festive plan: warm up, launch, scale, close\n42,000 WhatsApp sign-ups before the sale opened\nTiered offers kept new-season styles at full price\nStock-synced feed stopped ads on sold-out sizes',
      industry: 'Fashion & ethnic wear',
      market: 'India, tier 1 + tier 2',
      duration: '6-week festive campaign',
      channels: 'Meta Advantage+ Shopping, Catalog ads, Google PMax, WhatsApp',
      adSpend: '₹23L for the campaign',
      services: 'Campaign planning, Meta & Google Ads, Catalog ads, Creative production, WhatsApp retargeting',
      requirement: 'Urban Loom sells handloom-inspired ethnic wear to young working women. Last year\'s Diwali sale made ₹38L but ran out of steam after day three, and half the budget went into discounts the brand could not afford. They needed a festive campaign that would cross ₹1Cr in revenue while protecting margin.',
      goals: 'Cross ₹1Cr in festive-month revenue\nKeep ROAS above 4x for the whole sale, not just launch day\nGrow the WhatsApp list before the sale opened\nAvoid deep discounts on new-season styles',
      challenges: 'Sale fatigue | Last year\'s sale peaked on day one and fell sharply, because the same people saw the same "flat 40% off" ad all month.\nRising festive CPMs | Meta CPMs rise 60–80% in the weeks before Diwali, so cold prospecting during the sale is expensive.\n1,800-product catalog | Most products had a single flat-lay image, which made catalog ads look like a spreadsheet.\nStock risk | Bestsellers sold out mid-campaign last year while ads kept sending traffic to out-of-stock pages.',
      approach: 'Warm up before the rush | Started prospecting three weeks early, while CPMs were lower, and sent people to a WhatsApp early-access list instead of a sale page.\nTiered offers, not one discount | Early access got a gift with purchase, the main sale had discounts tiered by cart size, and new-season styles stayed full price.\nMake the catalog look good | Added lifestyle frames, price-drop overlays and creator try-on videos so dynamic ads felt like content.\nStock-aware ads | Synced the product feed with inventory every 6 hours, so sold-out sizes dropped out of ads automatically.',
      execution: 'The campaign ran in four phases: warm-up (weeks 1–3), early access (2 days), main sale (10 days) and last call (3 days). Each phase had its own creative, audiences and budget. A daily stand-up with the brand\'s ops team kept ads, stock and offers in sync.',
      deliverables: '6-week festive media plan with phase budgets\n90+ ad creatives, including creator try-on videos\nEnhanced catalog with lifestyle frames and price overlays\n42,000-person WhatsApp early-access list\nStock-synced product feed for Meta and Google',
      work: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=85 | Store and lookbook shoot for the festive catalog\nhttps://images.unsplash.com/photo-1607082349566-187342175e2f?auto=format&fit=crop&w=1200&q=85 | Tiered sale creative: cart-size offers instead of flat discounts\nhttps://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=85 | New-season edit, kept at full price through the sale',
      metrics: '₹1.2Cr | Festive revenue | in 30 days\n5.2x | Campaign ROAS | across Meta and Google\n42K | WhatsApp sign-ups | before launch\n+18% | Gross margin | vs last festive sale',
      comparison: 'Festive revenue | ₹38L | ₹1.2Cr\nCampaign ROAS | 2.7x | 5.2x\nAverage order value | ₹1,450 | ₹2,180\nRevenue after day 3 | 22% of total | 61% of total\nOrders from WhatsApp list | 0 | 9,800',
      resultsSummary: 'Warming up early meant Urban Loom entered Diwali week with 42,000 people already waiting. The sale earned three times last year\'s revenue, and because new-season styles stayed full price, gross margin went up too.',
      quote: 'Last Diwali we were refreshing the dashboard and hoping. This year we had a plan for every single day, and the sale kept growing instead of dying after the first weekend.',
      quoteName: 'Founder',
      quoteRole: 'Urban Loom',
      learnings: 'Win the sale before it starts | The cheapest customers came from the warm-up weeks, before festive CPMs peaked.\nTiered offers protect margin | Cart-size tiers raised order value without discounting the whole catalog.\nOps is part of performance | Syncing stock with the feed saved budget that would have gone to sold-out products.',
    },
    {
      brand: 'SkillSprint Academy',
      category: 'EdTech / Lead generation',
      headline: 'Cost per enrolment down 61% with a webinar funnel.',
      result: '-61% cost per enrolment',
      accent: '#003AA3',
      image: u('photo-1522202176988-66273c2fd55f', 1400),
      detail: 'SkillSprint was buying leads that never picked up the phone. We replaced instant-form lead ads with a free live masterclass funnel, qualified leads before sales called them, and cut the cost of a paid enrolment by 61%.',
      highlights: 'Instant forms replaced with a live masterclass funnel\nEvery lead scored before sales picked up the phone\nCRM outcomes sent back to Meta to train bidding\nFirst call in 12 minutes instead of 26 hours',
      industry: 'EdTech, upskilling courses',
      market: 'India, working professionals',
      duration: '5 months',
      channels: 'Meta Lead Ads, YouTube, Google Search, WhatsApp',
      adSpend: '₹12L / month',
      services: 'Funnel strategy, Meta & YouTube Ads, Landing pages, Lead scoring, CRM & WhatsApp automation',
      requirement: 'SkillSprint runs a 16-week data analytics course priced at ₹45,000. Their Meta lead ads brought in cheap leads at ₹90 each, but fewer than 1% enrolled, and the sales team was burning out calling people who did not remember filling in the form. They asked us to lower the cost of an actual enrolment, not the cost of a lead.',
      goals: 'Cut cost per paid enrolment by at least 40%\nRaise lead-to-enrolment rate above 3%\nGive the sales team fewer, better leads\nTrack every enrolment back to the ad that started it',
      challenges: 'Cheap leads, no buyers | Instant forms made sign-up effortless, so many leads were students and job seekers who could not afford the course.\nNo link from ad to sale | Enrolments closed on the phone, so Meta never learned which leads became paying students.\nSlow follow-up | Leads waited 26 hours on average for a first call, by which time interest had faded.\nLong decision cycle | A ₹45,000 course takes 2–3 weeks to decide on, but ads were judged on 7-day results.',
      approach: 'Sell the masterclass, not the course | Ads offered a free 90-minute live masterclass on analytics careers, so people showed real intent by giving up an evening.\nQualify on the landing page | A short form asked about experience, salary band and start date, and scored every lead before it reached sales.\nSend sales data back to Meta | Connected the CRM through the Conversions API, so "attended", "qualified" and "enrolled" events trained the algorithm on buyers.\nFollow up within minutes | WhatsApp reminders before each masterclass, and a sales call assigned within 15 minutes of attending.',
      execution: 'Two masterclasses ran every week. Ads drove registrations, WhatsApp handled reminders, and sales only called people who attended and scored as qualified. Every Friday we reviewed cost per attendee, attendance rate and enrolments by ad, and moved budget accordingly.',
      deliverables: 'Masterclass funnel: landing page, registration flow and thank-you page\nLead scoring model inside the CRM\nOffline conversions sent to Meta and Google\nWhatsApp reminder and nurture sequences\n60+ video ads, including faculty and alumni stories',
      work: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=1200&q=85 | Masterclass landing page, built and A/B tested in-house\nhttps://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=85 | Live masterclass sessions, run twice a week\nhttps://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=1200&q=85 | Funnel wireframe: ad → masterclass → qualified call',
      metrics: '-61% | Cost per enrolment | in 5 months\n4.2% | Lead-to-enrolment rate | up from 0.8%\n47% | Masterclass attendance | of registrations\n12 min | Time to first call | down from 26 hours',
      comparison: 'Cost per lead | ₹90 | ₹185\nLead-to-enrolment rate | 0.8% | 4.2%\nCost per enrolment | ₹11,250 | ₹4,400\nEnrolments per month | 107 | 273\nSales calls per enrolment | 125 | 24',
      resultsSummary: 'Leads became more expensive, and that was the point. Each lead now costs ₹185 instead of ₹90, but five times more of them enrol, so the cost of a paying student fell by 61% and monthly enrolments more than doubled on the same budget.',
      quote: 'We stopped judging marketing on cost per lead. Our sales team now talks to people who actually showed up and want to learn, and our enrolments have more than doubled.',
      quoteName: 'Head of Sales',
      quoteRole: 'SkillSprint Academy',
      learnings: 'Optimise for the sale, not the lead | Cheaper leads looked good in Ads Manager and bad in the bank account.\nFriction filters | Asking people to attend a live session removed low-intent leads before sales spent time on them.\nSpeed wins deals | Calling within 15 minutes of the masterclass made the biggest single difference to enrolments.',
    },
    {
      brand: 'Aranya Homes',
      category: 'Real estate / Lead generation',
      headline: '3,200 qualified leads for a new project launch.',
      result: '-55% cost per lead',
      accent: '#FFDE59',
      image: u('photo-1600585154340-be6161a56a0c', 1400),
      detail: 'Aranya Homes needed site visits for a new 2 and 3 BHK project in Pune. We ran Google Search, Meta and YouTube into one tightly qualified funnel and delivered 3,200 qualified leads at 55% lower cost per lead than their previous launch.',
      highlights: 'Locality and commute keywords instead of city-wide terms\nBudget, timeline and loan questions in every lead form\nDrone and walkthrough videos answered questions early\n41 units sold in the launch window',
      industry: 'Real estate developer',
      market: 'Pune, Mumbai & NRI buyers',
      duration: '4-month launch',
      channels: 'Google Search, Meta Lead Ads, YouTube, WhatsApp',
      adSpend: '₹15L / month',
      services: 'Launch media plan, Google & Meta Ads, Lead qualification, Landing pages, Sales reporting',
      requirement: 'Aranya was launching a 240-unit project in Pune. Their previous launch, run through property portals and brokers, cost ₹2,900 per lead, and the sales team said most leads were "just browsing". They wanted leads who could afford an ₹85L–1.4Cr home, and site visits booked every weekend.',
      goals: 'Generate 3,000+ qualified leads in four months\nKeep cost per qualified lead under ₹2,500\nBook 60+ site visits a month\nReach NRI buyers in the Gulf and the US',
      challenges: 'Junk leads | Earlier lead ads brought in renters, brokers and people with budgets far below the project price.\nExpensive keywords | Searches like "2 BHK in Pune" cost ₹60–90 per click and were shared with every developer in the city.\nLong buying cycle | Home buyers take 3–6 months to decide, so leads had to be nurtured, not just collected.\nNo feedback loop | Sales tracked lead status in spreadsheets, so the ad platforms never knew which leads were real.',
      approach: 'Target micro-markets | Built search campaigns around specific localities, commute routes and IT parks near the project instead of generic city keywords.\nQualify inside the form | Lead forms asked about budget, timeline and home loan status, adding a step on purpose to filter out casual browsers.\nWalkthrough-first creative | Used drone footage, sample flat walkthroughs and price-per-sq-ft breakdowns, so the ad answered questions before the call.\nClose the loop | Moved sales onto a simple CRM and sent "qualified" and "site visit" events back to Google and Meta every day.',
      execution: 'Campaigns went live three weeks before the sales office opened, building a waitlist for launch pricing. After launch, weekday ads drove enquiries and weekend ads pushed site visit bookings. Our team joined the developer\'s sales review every Monday to match ad data with feedback from the ground.',
      deliverables: 'Locality-led Google Search structure with 40 ad groups\nLaunch landing page with floor plans and an EMI calculator\nDrone and walkthrough video ads for Meta and YouTube\nNRI campaigns for the UAE, Saudi Arabia and the US\nDaily CRM sync with offline conversions',
      work: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=85 | Sample flat walkthrough used across Meta and YouTube ads\nhttps://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1200&q=85 | Launch-offer creative for weekend site visit bookings\nhttps://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=1200&q=85 | Weekly sales review with the developer\'s team',
      metrics: '3,200 | Qualified leads | in 4 months\n-55% | Cost per lead | vs previous launch\n310 | Site visits | booked from ads\n41 | Units sold | in the launch window',
      comparison: 'Cost per lead | ₹2,900 | ₹1,300\nQualified lead rate | 31% | 70%\nCost per qualified lead | ₹9,350 | ₹1,860\nSite visits per month | 22 | 78\nUnits sold in launch window | 14 | 41',
      resultsSummary: 'Harder questions in the form cut the junk, and sending sales outcomes back to the ad platforms taught them what a real buyer looked like. Aranya sold 41 units in the launch window, almost three times their previous launch.',
      quote: 'For the first time, our sales team asked marketing for more leads instead of complaining about them. Weekend site visits have been full since the second month.',
      quoteName: 'Sales Director',
      quoteRole: 'Aranya Homes',
      learnings: 'Quality is a targeting setting | Once the platforms received qualified-lead data, cost per qualified lead fell month on month.\nLocal beats generic | Locality and commute keywords converted at twice the rate of "flats in Pune".\nShow the home before the call | Walkthrough videos produced leads who already knew the price and layout.',
    },
    {
      brand: 'FitPulse',
      category: 'Fitness app / App growth',
      headline: 'Nearly 2x paying subscribers on the same budget.',
      result: '-48% cost per subscriber',
      accent: '#003AA3',
      image: u('photo-1517836357463-d25dfeac3438', 1400),
      detail: 'FitPulse had plenty of installs but few paying subscribers. We moved app campaigns from install bidding to trial and subscription events, rebuilt creative around real workouts, and cut the cost of a paying subscriber by 48%.',
      highlights: 'Bidding moved from installs to trials and subscriptions\nSubscription tracking fixed on Android and iOS\n120+ real workout videos replaced stock footage\nInstall-to-paid rate up from 1.5% to 3.4%',
      industry: 'Health & fitness app',
      market: 'India, Android + iOS',
      duration: '5 months',
      channels: 'Google App Campaigns, Meta App Ads, Apple Search Ads',
      adSpend: '₹10L / month',
      services: 'App campaign strategy, MMP & event setup, Creative production, App store optimisation, Retention ads',
      requirement: 'FitPulse offers home and gym workout plans on a ₹299 monthly subscription. Their campaigns delivered installs at ₹28 each, but only 1.5% of people who installed ever paid. The founders wanted growth in paying subscribers, with clear data on which campaigns brought in people who stayed.',
      goals: 'Cut cost per paying subscriber by 35% or more\nOptimise campaigns for trials and subscriptions, not installs\nImprove day-30 retention of paid users\nLift app store conversion rate',
      challenges: 'Optimising for the wrong event | Campaigns bid for installs, so the platforms found people who install apps but never pay.\nMessy event tracking | The MMP and Firebase reported different numbers, and the subscription event did not fire on iOS at all.\nGeneric creative | Stock-style gym footage looked like every other fitness app, with a hook rate under 15%.\nWeak store listing | Screenshots showed features instead of results, and the store page converted only 21% of visitors.',
      approach: 'Fix the events | Rebuilt tracking in the MMP and Firebase so trial start and paid subscription fired reliably on Android and iOS.\nBid for value | Moved Google App Campaigns to target CPA on trial start, then to subscription once volume allowed. Meta followed the same path.\nReal workouts, real people | Filmed 10-minute home workouts with trainers and members, cut into 15-second "try this" hooks.\nOptimise the store page | Tested new screenshots, a preview video and results-led copy on the Play Store and App Store.',
      execution: 'We ran fortnightly creative sprints of 15–20 new videos, with a weekly look at cohort data: cost per trial, trial-to-paid rate and day-30 retention by campaign. Budget only moved towards campaigns whose subscribers were still active after 30 days.',
      deliverables: 'MMP and Firebase event setup for trial and subscription\nGoogle App, Meta and Apple Search Ads campaigns rebuilt\n120+ workout-led video ads\nNew store screenshots and preview video\nCohort dashboard with day-30 retention by campaign',
      work: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1200&q=85 | Home workout shoot for the "try this in 10 minutes" ad series\nhttps://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1200&q=85 | Gym member stories filmed for retention ads\nhttps://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=85 | Cohort dashboard: subscribers still active after 30 days',
      metrics: '-48% | Cost per subscriber | in 5 months\n3.4% | Install-to-paid rate | up from 1.5%\n+43% | Store conversion rate | after listing tests\n+19% | Day-30 retention | of paid users',
      comparison: 'Cost per install | ₹28 | ₹33\nInstall-to-paid rate | 1.5% | 3.4%\nCost per paying subscriber | ₹1,870 | ₹970\nStore page conversion | 21% | 30%\nNew subscribers per month | 535 | 1,030',
      resultsSummary: 'Installs got slightly more expensive, but the people installing were far more likely to pay. FitPulse now adds almost twice as many paying subscribers each month on the same budget, and more of them are still working out after 30 days.',
      quote: 'We used to celebrate cheap installs. CLYX made us look at who actually pays and stays, and our subscriber growth has nearly doubled since.',
      quoteName: 'Co-founder',
      quoteRole: 'FitPulse',
      learnings: 'Bid for the event you are paid on | Moving from install to trial to subscription bidding changed who the algorithm found.\nShow the product working | Real workout clips beat polished brand videos on hook rate and on trial starts.\nThe store page is a landing page | Store listing tests lifted conversion on every channel at once.',
    },
  ],
  team: [
    { name: 'Arjun Chaudhary', role: 'Founder & CEO', bio: 'Leads the CLYX team and sets the strategic direction across performance, creative, and growth.', badge: '₹80Cr+ Scaled', img: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop' },
    { name: 'Sanya Malhotra', role: 'Head of Creator Strategy & UGC', bio: 'Directs 200+ creator relationships and content production frameworks that convert.', badge: '200+ Creators', img: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=600&auto=format&fit=crop' },
    { name: 'Karan Johar', role: 'Head of Conversion Tech & CRO', bio: 'Builds fast, conversion-first digital experiences where every interaction earns its place.', badge: '0.4s Sub-Second Web', img: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=600&auto=format&fit=crop' },
  ],
  testimonials: [
    { quote: 'CLYX completely replaced our internal creative bottleneck. Their creator whitelisting pipeline drove our ROAS from 2.1x to 4.4x in just six weeks.', name: 'Aarav Kapoor', role: 'Founder & CEO', brand: 'Lumina Skincare', metrics: '+265% Revenue · ₹1.2Cr Added' },
    { quote: 'Most agencies give you fluff reports and vanity metrics. CLYX treats our ad budget like their own money. The blend of UGC + performance buying is deadly.', name: 'Natasha Roy', role: 'Head of Growth', brand: 'Aethel Streetwear', metrics: '3.9x ROAS · ₹40L/month Scale' },
    { quote: 'The landing page they built loaded in 0.4 seconds. Coupled with their whitelisted creator ads, our checkout conversion rate jumped from 1.8% to 4.8%.', name: 'Devang Patel', role: 'Co-Founder', brand: 'Volt Audio', metrics: '5.1x Peak ROAS · 0.4s Page Speed' },
  ],
  blog: [
    { title: 'Why the best creator ads do not feel like ads', tag: 'Creator economy', date: '12.09.25', readTime: '4 min read', style: 'yellow', image: u('photo-1611926653458-09294b3142bf') },
    { title: 'The performance creative loop, explained', tag: 'Performance', date: '04.09.25', readTime: '6 min read', style: 'blue', image: u('photo-1551288049-bebda4e38f71') },
    { title: 'From scroll-stopping hook to scalable system', tag: 'Growth', date: '28.08.25', readTime: '5 min read', style: 'soft', image: u('photo-1432888498266-38ffec3eaf0a') },
    { title: 'The page is part of the ad', tag: 'CRO', date: '19.08.25', readTime: '3 min read', style: 'yellow', image: u('photo-1547658719-da2b51169166') },
    { title: 'What to do when everything is working a little', tag: 'Strategy', date: '11.08.25', readTime: '5 min read', style: 'blue', image: u('photo-1552664730-d307ca884978') },
    { title: 'Briefing for a voice, not a demographic', tag: 'Creators', date: '02.08.25', readTime: '4 min read', style: 'soft', image: u('photo-1478737270239-2f02b77fc618') },
  ],
  careers: [
    { title: 'Performance Marketing Lead', type: 'Full-time / Remote', detail: 'Own the decisions that turn winning creative into efficient growth.', department: 'Growth', experience: '4+ years' },
    { title: 'Creator Partnerships Manager', type: 'Full-time / Mumbai or Remote', detail: 'Build the relationships and systems behind our creator network.', department: 'Creators', experience: '2+ years' },
    { title: 'Conversion Designer', type: 'Contract / Remote', detail: 'Shape the pages, offers, and interactions that turn attention into action.', department: 'Design', experience: '3+ years' },
  ],
  creators: [
    'photo-1534528741775-53994a69daeb',
    'photo-1517841905240-472988babdf9',
    'photo-1539571696357-5a69c17a67c6',
    'photo-1524504388940-b1c1722653e1',
    'photo-1507003211169-0a1dd7228f2d',
    'photo-1494790108377-be9c29b29330',
    'photo-1500648767791-00dcc994a43e',
    'photo-1522075469751-3a6694fb2f61',
    'photo-1488426862026-3ee34a7d66df',
    'photo-1519085360753-af0119f7cbe7',
    'photo-1506794778202-cad84cf45f1d',
    'photo-1492562080023-ab3db95bfbce',
  ].map((id) => ({ image: u(id, 800) })),
  courses: [
    {
      title: 'Creator Ads Masterclass',
      tagline: 'Turn short-form clips into ads that sell: hooks, scripts, edits and whitelisting, taught live by the CLYX team.',
      price: '29',
      originalPrice: '999',
      image: u('photo-1611926653458-09294b3142bf'),
      badge: 'Live batch',
      duration: '4 weeks',
      format: 'Live classes',
      level: 'Beginner to intermediate',
      schedule: 'Weekend live sessions, 7 PM IST',
      highlights: [
        'Write hooks that stop the scroll in the first 2 seconds',
        'Script and brief creators for ads, not just content',
        'Edit for retention: pacing, captions and pattern breaks',
        'Whitelisting basics: run creator posts as paid ads',
      ].join('\n'),
      includes: ['Live classes', 'Class recordings to rewatch', 'Hook and script templates', 'WhatsApp support from the team'].join('\n'),
      description: '',
    },
    {
      title: 'Meta Ads from Zero',
      tagline: 'Set up, test and scale Meta ads the way we run them for D2C brands, from first campaign to steady ROAS.',
      price: '49',
      originalPrice: '1499',
      image: u('photo-1551288049-bebda4e38f71'),
      badge: 'New',
      duration: '6 weeks',
      format: 'Live classes',
      level: 'Beginner',
      schedule: 'Weekday evening live sessions, 8 PM IST',
      highlights: [
        'Account, pixel and conversion setup done right',
        'Campaign structure that is easy to test and scale',
        'Reading the numbers: CTR, CPA, ROAS and what to change',
        'Creative testing loops that keep winners coming',
      ].join('\n'),
      includes: ['Live classes', 'Class recordings to rewatch', 'Campaign planning sheet', 'WhatsApp support from the team'].join('\n'),
      description: '',
    },
  ],
  portfolio: [
    { title: 'Kulture Skin', category: 'Beauty', result: '3.4x ROAS', image: u('photo-1522337360788-8b13dee7a37e') },
    { title: 'Nova Nutrition', category: 'Food', result: '42% lower CPA', image: u('photo-1541643600914-78b084683601') },
    { title: 'Mutha Beauty', category: 'Fashion', result: '10M+ impressions', image: u('photo-1515886657613-9f3515b0c78f') },
    { title: 'Orbit Labs', category: 'Tech', result: '+28% CVR lift', image: u('photo-1460925895917-afdab827c52f') },
    { title: 'Halo Goods', category: 'D2C', result: '4.1x blended ROAS', image: u('photo-1496747611176-843222e1e57c') },
    { title: 'Aura Collective', category: 'Fashion', result: '+188% CTR', image: u('photo-1483985988355-763728e1935b') },
    { title: 'Glow Theory', category: 'Beauty', result: '2.8x ROAS', image: u('photo-1596462502278-27bfdc403348') },
    { title: 'Fresh Fork', category: 'Food', result: '3.1x ROAS', image: u('photo-1504674900247-0877df9cc836') },
    { title: 'Thread Society', category: 'Fashion', result: '3.8x ROAS', image: u('photo-1490481651871-ab68de25d43d') },
    { title: 'Pixel Stack', category: 'Tech', result: '+34% CVR lift', image: u('photo-1518770660439-4636190af475') },
    { title: 'Tick Theory', category: 'D2C', result: '3.6x ROAS', image: u('photo-1523275335684-37898b6baf30') },
    { title: 'Dewdrop Labs', category: 'Beauty', result: '+64% repeat orders', image: u('photo-1571781926291-c477ebfd024b') },
    { title: 'Slice House', category: 'Food', result: '+72% online orders', image: u('photo-1565299624946-b28f40a0ae38') },
    { title: 'Luxe Lane', category: 'Fashion', result: '+96% CTR', image: u('photo-1445205170230-053b83016050') },
    { title: 'DataPulse', category: 'Tech', result: '2.9x pipeline', image: u('photo-1551288049-bebda4e38f71') },
    { title: 'Stride Co', category: 'D2C', result: '+140% sales', image: u('photo-1542291026-7eec264c27ff') },
    { title: 'Blush & Co', category: 'Beauty', result: '6.2M views', image: u('photo-1512496015851-a90fb38ba796') },
    { title: 'Green Bowl Co', category: 'Food', result: '5M+ impressions', image: u('photo-1512621776951-a57141f2eefd') },
    { title: 'Muse Studio', category: 'Fashion', result: '8M+ reach', image: u('photo-1469334031218-e382a71b716b') },
    { title: 'CodeCraft', category: 'Tech', result: '45% lower CPL', image: u('photo-1498050108023-c5249f4df085') },
    { title: 'SoundNest', category: 'D2C', result: '29% lower CPA', image: u('photo-1505740420928-5e560c06d30e') },
    { title: 'Pure Ritual', category: 'Beauty', result: '38% lower CAC', image: u('photo-1570172619644-dfd03ed5d881') },
    { title: 'Harvest Kitchen', category: 'Food', result: '35% lower CPA', image: u('photo-1546069901-ba9599a7e63c') },
    { title: 'Noir Atelier', category: 'Fashion', result: '31% lower CPA', image: u('photo-1509631179647-0177331693ae') },
    { title: 'Nimbus Cloud', category: 'Tech', result: '+210% sign-ups', image: u('photo-1519389950473-47ba0277781c') },
    { title: 'Frame & Lens', category: 'D2C', result: '4.4x ROAS', image: u('photo-1526170375885-4d8ecf77b99f') },
    { title: 'Velvet Skin', category: 'Beauty', result: '+152% CTR', image: u('photo-1608248597279-f99d160bfcbc') },
    { title: 'Morning Stack', category: 'Food', result: '2.6x ROAS', image: u('photo-1567620905732-2d1ec7ab7445') },
    { title: 'Byte Wave', category: 'Tech', result: '3.2x ROAS', image: u('photo-1531297484001-80022131f5a1') },
    { title: 'Shade Club', category: 'D2C', result: '+81% CTR', image: u('photo-1572635196237-14b3f281503f') },
  ],
};
